kcmutils: Autospec creation for update from version 5.115.0 to version 6.0.0
Albert Astals Cid (1):
      Use CLASS_NAME instead of CLASSNAME

Alexander Lohnau (128):
      Delete ServiceTypes for KCModule/KCModuleInit
      Remove deprecated code
      Restore deleted autotest
      Remove unused string list
      Port away from kcoreaddons_desktop_to_json in autotests
      Clean up preparetips leftover in Messages.sh
      Import kcmshell from kde-cli-tools
      Rename kcmshell executable, make it build against Qt6, cleanup
      Move kcmshell to src rather than tools
      GIT_SILENT Add missing dependency to kde-ci.yml
      Fix windows build
      kcmshell: Fix weird/broken setting of dbus service name
      Fix windows issues for kcmshell
      Simplify KCMultiDialog
      Import KCModule and ConfigModule/ManagedConfigModule classes
      Remove deprecated code from imported classes
      Start adjusting export macros and includes of qml configmodule files
      KCModuleQml: Port to copied ConfigModule class
      Compile KCModule as part of KCMUtils
      qml/configmodule: Clean up QQC1 workaround
      qml/configmodule: Clean up remaining KAboutData API
      qml/configmodule: Do not put QtQml include in public header
      Exctract universal properties from QML ConfigModule to KAbstractConfigModule
      KCModule: Remove KAboutData from public API
      KCModule: Start porting to KAbstractConfigModule
      Adjust code to KCModule changes, remove KCModuleProxy
      GIT_SILENT Fix small build system issues
      Adjust to shared engine being no longer in Kirigami
      Make kcmshell6 compile
      Create new QML engine as fallback
      Fix crash on delete
      Introduce KCModuleLoader QML to have consistent entry point
      KCModuleLoader: Make error reporting completely internal
      Rename classes from KDeclarative
      Rename KCMUtils target containing QML/QtQuick classes
      KCModuleQml: Small refactorings/cleanups
      Update docs for QML KCMS
      KCMultiDialog: Rename method in p-impl
      Remove KAuth code for KCModule/KCMultiDialog
      Add kpackage dependency to .kde-ci.yml file
      Remove KAbstractConfigModule::setNeedsAuthorization
      KQuickConfigModule: Fix undefined behaviour by adding missing initialization of pointer
      Enable POSITION_INDEPENDENT_CODE for static logging lib
      Register KQuickConfigModule to QML, configure QML name
      Only create QQmlEngine on demand and not when loading QWidgets KCM
      Remove some unused/rarely used API
      Small cleanups
      ManagedConfigModule: Do not use Q_PRIVATE_SLOT, simplify code
      KQuickConfigModule: Store KPackage in d-ptr, instead of loading mutiple times
      Avoid verbose FWD, add include guards for KQuickConfigModuleLoader
      Small code cleanups
      Review/Update docs for KF6::KCMutils classes
      KCModule: Fix registration of plugins when taking a QWidget as a parent
      KCModule: Enforce all constructor args to be initialized
      Utilize ecm_add_qml_module for QML plugin
      Do not install dummy plugins, use kcoreaddons_add_plugin
      Fix KCMUtilsQml leftovers
      KCModule: Add markAsChanged method back for easier signal connect
      Download missing licenses
      Add Qt6Qml to cmake config
      Clean up linking of KF6KCMUtils module
      Add utility constructor for KCModule
      Add Q_OBJECT macro to QmlConfigModuleWidget
      Remove KService dependency from CMake config
      Fix sizehint and QML KCMs not recieving click events
      KCModuleQML: Also include logic to load on first show
      KCModule: Be call base class load/save/defaults methods
      Move KCModuleData to KCMutilsCore
      Consistently use std::unique_ptr for d-ptr
      KCModuleData: Remove virtual hook
      KF6KCMUtilsQuick: Link to KF6::ConfigCore instead of ConfigGui
      Remove prefix from KConfigCore include
      Make KCModule::load call not depend on Widget's first show
      Add more debug logs to fake KCMs
      KCMultiDialog: Call KCModule::load in next iteration of event loop
      Add cmake function to bundle QML files as QRC in KCM
      KCModuleQml: Load KCMs QML files using qrc
      kcmutils_generate_module_data: Allow usage of target instead of sources list
      SharedQmlEnginePrivate::execute: Add assertion for source not being empty
      KF6KCMUtilsMacros: Avoid recompiling qrc files after reconfiguring
      Allow loading of KPackage KCms for now
      Add simple test to make sure QML KCMs load
      Add test for fallback KCM being shown
      Skip failing test for now due to CI dependencies
      Remove debug leftover in autotests
      KF6KCMUtilsMacros: Document that target can be used in kcmutils_generate_module_data
      KF6KCMUtilsMacros: Add prefix for parsed variable
      Make QVariantList arg optional for constructors
      KF6KCMUtilsMacros: Show error message if no QML sources are found
      kcmshell: Remove dbus registration of modules
      kcmshell: General code cleanup
      kcmshell: Show error if KCM is not found
      kcmshell: Allow loading of KCMs by path with empty metadata
      Import org.kde.kcm files from KDeclarative
      Install QML files of imported KDeclarative classes, adjust docs
      Rename KPluginSelector.qml/KPluginDelegate.qml to PluginSelector.qml/PluginDelegate.qml
      Import KCMShell class from KDeclarative
      Remove unneeded authorize method of KCMShell
      Rename KCMShell QML class to KCMLauncher
      Add KIO to dependencies, fix some QML plugin issues
      KCMLauncher: Use kcmshell6 instead of kcmshell5
      Update QML code snippet in KQuickConfigModule
      Update QML component docs
      Remove KPackage compat code
      Remove QVariantList argument from KCM constructor args
      Remove unused QVariantList argument from KCModuleData constructor
      KQuickConfigModule: Destroy view before attached KCM object
      Make KQuickConfigModule constructor protected
      Fix some QML elements being rendered after delay
      KPluginSelector.qml: Fix broken Kirigami.OverlaySheet usage
      KPluginWidget: Explicitly call KCModule::load before showing KCM
      ContextualHelpButton: Convert license header to SPDX
      Remove unused LGPL-3.0-or-later license file
      Add missing licenses to source files
      Clean up no longer needed test files
      Remove unneeded statements from license headers
      Simplify JSON of fake KCM file
      Add SPDX info to some test files
      kcmshell6: Remove reference of deprecated option
      ContextualHelpButton: Relicense file to LGPL-2.0-or-later
      KPluginModel: Keep order of categories as they were
      KPluginModel: Allow consumers to implement custom drag/drop sorting
      Fix AboutDialog in case delegate is intermediate Item
      kcmshell6: Use KShell to split values coming from args option
      KCModuleLoader/KQuickConfigModuleLoader: Avoid putting json array in args
      Remove code for generating pri file
      KAbstractConfigModule: Avoid module include in public header
      Add explicit moc include to generated KCModuleData impl

Arjen Hiemstra (1):
      qml: Port PluginDelegate away from Kirigami.BasicListItem

Carl Schwan (3):
      Don't overwrite margin of QDialogButtonBox
      Improve style of KPluginWidget
      Fix spacing of the dialog button box

David Faure (1):
      Port to ECMFeatureSummary

Friedrich W. H. Kossebau (9):
      Update LINK_QCHS to Qt6 versions
      Drop removed file from QCH sources
      Adapt to changed KWidgetItemDelegate::updateItemWidgets signature
      Use more explicit constructors
      Set target properties right after declaring the target
      Generate version header on src/ level
      Have export macros header include version header
      Add missing include guards
      Add explicit moc includes to sources for moc-covered headers

Fushan Wen (11):
      kcmoduleqml: set `Qt::WA_NoMousePropagation` to fix drag everywhere
      GridDelegate: lazy load menu
      qml: install `private/GridDelegateMenu.qml`
      GridDelegateMenu: fix unable to create component
      PluginSelector: set about dialog parent to root contentItem
      qml: simplify `SettingHighlighterPrivate`
      kcmshell: focus on content area by default
      GridDelegate: set default Accessible.description
      ScrollView: bind view's KeyNavigation.up to global toolbar
      PluginDelegate: set domain for i18n strings
      AboutPlugin: update domain for i18n strings

Harald Sitter (1):
      do not singleshot without context object

Heiko Becker (1):
      GIT_SILENT Upgrade Qt6 version requirement to 6.5.0.

Ismael Asensio (5):
      KCMultidialog: Expose method to show non-defaults indicators
      KCMShell: Add an option to show non-defaults indicators
      KAbstractConfigModule: Allow updating arguments on a running module
      GridDelegate: Fix title text color when disabled
      GridDelegate: Fix ring color for disabled items

Jakob Petsovits (1):
      SharedQmlEngine: Don't crash from dangling child item objects

Jonathan Esk-Riddell (12):
      Update version number for 5.245.0
      Update version number for 5.246.0
      Update version number for 5.247.0
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release
      update version for new release

Laurent Montel (4):
      GIT_SILENT: fix extra-cmake-modules url
      Use kcmshell6 in kf6
      GIT_SILENT: Remove mention of qmake library from metainfo.yaml
      GIT_SILENT: Port to new CI template

Luigi Toscano (1):
      Fix the translation template version number (5->6)

Marco Martin (1):
      Introduce the sidebar mode for kcms

Méven Car (2):
      Add KQuickManagedConfigModule::mainUiReady signal
      Fix warning: implicit capture of ‘this’ via ‘[=]

Nate Graham (1):
      AbstractKCM: remove footer line for unframed KCMs w/o extra footer padding

Nicolas Fella (12):
      Set systemsettings as alias when generating desktop files
      Remove Qt5 CI
      Require Qt6
      Update KF_VERSION for KF6 development
      Rename CMake targets/config/libraries for KF6
      Bump KF_DEP_VERSION for KF6
      Add missing find_dependency for KCoreAddons
      Uset QApplication::applicationDisplayName
      [kpluginwidget] Fix parent handling for plugin KCMs
      Sync authActionName and representsDefaults on creation of KCModuleQml
      Adapt to plasma-framework moving to Plasma
      Port away from KActivities

Oliver Beard (1):
      SimpleKCM: Don't show header separator on overflow

Tobias Fella (2):
      Remove dead X-KDE-PluginKeyword code
      Show GridDelegate labels as plaintext

Vlad Zahorodnii (3):
      Fix KCMultiDialog not saving modified configs
      Fix icons in KPluginDelegate
      Provide dummy incubation controller

Volker Krause (4):
      Remove Qt 5 support
      KF::CoreAddons (for KPluginMetaData) needs to be in public link interface
      Replace QVector by QList
      Bump Qt deprecation level to 6.5

ivan tkachenko (36):
      Remove obsolete header
      Fix comment: use punctuation for readability for sentences.
      KCModuleQml: Specify URL for root component's QML context
      KCModuleQml: Explicitly specify signal handler arguments
      Add Q_OBJECT macro to KCModuleProxyInternal
      Use ellipses instead of triple period
      KAbstractConfigModule: Fix type of property defaultsIndicatorsVisible
      KCModuleQml: Fix setting defaults indicator of child QML module
      KCModuleQml: Set and inherit LayoutMirroring on an off-screen window
      KCModuleQml: Fix event filter object
      KPluginDelegate: Clean up QML/JS code style, bump imports
      KQuickConfigModule: Narrow down type of keys in s_rootObjects hash
      KQuickConfigModule: Improve code snippet in doc comment
      KCModuleQml: Narrow down type of kcm context property
      KCModuleQml: Fix whitespace
      KCModuleQml: Use common QQC2 alias for Controls import
      KCModuleQml: Drop QML import versions
      KQuickConfigModule: Use qmlContext() shorthand
      KQuickConfigModule: Drop underscore prefixes from private class' members
      SharedQmlEngine: Factor out rootObject() calls
      KCMError: Bigger header and text selection for everything
      PluginDelegate: Fix up leftover issues after porting
      PluginDelegate: Add leading item property for backward compatibility
      PluginDelegate: Fix eliding text
      PluginDelegate: Defend against null model object
      AbstractKCM: Port layout to the new Padding type, fix separators
      ScrollViewKCM: Clip Flickable content whenever there is a header and/or a footer
      Get rid of custom incubator, make initialProperties map truly initial
      SettingHighlighterPrivate: Declare QQmlParserStatus interface
      SharedQmlEngine: Get rid of unnecessary incubator
      SharedQmlEngine: Improve errors reporting
      SharedQmlEngine: Use built-in operator<< for printing QQmlError
      SharedQmlEngine: Get rid of quotes around indentation spaces
      SharedQmlEngine: Remove superfluous cast of QQmlComponent::Status
      SharedQmlEngine: Inline QTimer object
      Add logging category to warnings

l10n daemon script (152):
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn
      GIT_SILENT Sync po/docbooks with svn